spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practicedb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      
server:
  tomcat:
    threads:
      max: 200
  port: 8151